[package]
name = "rust_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-sdk = "3.0.0"
solana-client = "3.1.2"
solana-program = "3.0.0"
solana-system-transaction = "3.0.0"